### ISSUE TITLE
Appliquer le style guide sur le Body

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#44]

**Comment by luclemo** [comment]
Nice work on the visuals :)

Same overall comment as the feedback in #43: you need to  use proper html elements for content (not `div` for everything) in order to meet basic accessibility guidelines. 

## Markup
- Use proper markup/elements for typography (`h1, h2, h3 …`, `p` etc)
- Use `a` tags for links. This includes
  - the portal link below the search form
  - The cards that lead to docs
  - footer links etc

## Links

### Ancor link
- "Acces au portail" link should be styled with CSS `border-bottom`:
  - default: 1px dotted
  - hover: 1px solid

### Card links
- First card is styled in the hover state
- Color of text in default states of the three cards is wrong (see mockups)
- Circle from icon in SVG should be white when card is in hover state (see mockups)
  - either swap the image or embed the svg icons and change the fill of `.spot` on hover

As it stands, the way the cards are coded it will not be scaleable if content is longer or shorter. I have coded a demo here as a starting point: https://codepen.io/luclemo/pen/b111a9a7b850438bd564c47d412f1e40

## Search form 
- Style all states for input (see mockup specs)
- Button text color is wrong
- Style hover states for button

**Comment by luclemo** [comment]
Looks good!
